name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Build and push backend Docker image
      - name: Build and push backend
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          docker build -t aakinonigbinde/backend:latest ./backend
          echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
          echo ${{ secrets.DOCKER_HUB_USERNAME }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}-stdin
          docker push yourdockerhubusername/backend:latest

      # Build and push frontend Docker image
      - name: Build and push frontend
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          docker build -t aakinonigbinde/frontend:latest ./frontend
          echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
          docker push yourdockerhubusername/frontend:latest

      # SSH into VPS and deploy containers using Docker Compose
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
            docker login -u "$DOCKER_HUB_USERNAME" --password-stdin <<< "${{ secrets.DOCKER_HUB_PASSWORD }}"
            docker pull yourdockerhubusername/backend:latest
            docker pull yourdockerhubusername/frontend:latest
            docker-compose -f /path/to/your/docker-compose.yml up -d
